replicaCount: 1

image:
  repository: raisalsalim/nodejs-app
  tag: "53"
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  nodePort: 30009

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: nodejs-app.local
      paths: ["/"]
  tls: []

resources: {}
