# clusters/minikube/flux-system/gitrepository.yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: nodejs-app
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/raisalsalim/nodejs-app-helm-flux.git
  ref:
    branch: main
  secretRef:
    name: flux-system
